INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (1, 'Qatar', 'Qatar', 'contact@qatar.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (2, 'Ecuador', 'Ecuador', 'contact@ecuador.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (3, 'Senegal', 'Senegal', 'contact@senegal.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (4, 'Netherlands', 'Netherlands', 'contact@netherlands.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (5, 'England', 'England', 'contact@england.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (6, 'Iran', 'Iran', 'contact@iran.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (7, 'USA', 'USA', 'contact@usa.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (8, 'Wales', 'Wales', 'contact@wales.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (9, 'Argentina', 'Argentina', 'contact@argentina.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (10, 'Saudi Arabia', 'Saudi Arabia', 'contact@saudiarabia.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (11, 'Mexico', 'Mexico', 'contact@mexico.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (12, 'Poland', 'Poland', 'contact@poland.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (13, 'France', 'France', 'contact@france.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (14, 'Australia', 'Australia', 'contact@australia.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (15, 'Denmark', 'Denmark', 'contact@denmark.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (16, 'Tunisia', 'Tunisia', 'contact@tunisia.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (17, 'Spain', 'Spain', 'contact@spain.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (18, 'Costa Rica', 'Costa Rica', 'contact@costarica.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (19, 'Germany', 'Germany', 'contact@germany.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (20, 'Japan', 'Japan', 'contact@japan.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (21, 'Belgium', 'Belgium', 'contact@belgium.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (22, 'Canada', 'Canada', 'contact@canada.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (23, 'Morocco', 'Morocco', 'contact@morocco.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (24, 'Croatia', 'Croatia', 'contact@croatia.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (25, 'Serbia', 'Serbia', 'contact@serbia.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (26, 'Switzerland', 'Switzerland', 'contact@switzerland.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (27, 'Cameroon', 'Cameroon', 'contact@cameroon.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (28, 'Portugal', 'Portugal', 'contact@portugal.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (29, 'Ghana', 'Ghana', 'contact@ghana.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (30, 'Uruguay', 'Uruguay', 'contact@uruguay.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (31, 'South Korea', 'South Korea', 'contact@southkorea.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (32, 'Italy', 'Italy', 'contact@italy.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (33, 'Turkey', 'Turkey', 'contact@turkey.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (34, 'Scotland', 'Scotland', 'contact@scotland.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (35, 'Czech Republic', 'Czech Republic', 'contact@czechrepublic.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (36, 'Slovakia', 'Slovakia', 'contact@slovakia.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (37, 'Hungary', 'Hungary', 'contact@hungary.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (38, 'Russia', 'Russia', 'contact@russia.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (39, 'Austria', 'Austria', 'contact@austria.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (40, 'North Macedonia', 'North Macedonia', 'contact@northmacedonia.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (41, 'Brazil', 'Brazil', 'contact@brazil.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (42, 'Colombia', 'Colombia', 'contact@colombia.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (43, 'Chile', 'Chile', 'contact@chile.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (44, 'Peru', 'Peru', 'contact@peru.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (45, 'Paraguay', 'Paraguay', 'contact@paraguay.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (46, 'Bolivia', 'Bolivia', 'contact@bolivia.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (47, 'Venezuela', 'Venezuela', 'contact@venezuela.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (48, 'Real Madrid', 'Spain', 'contact@realmadrid.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (49, 'Barcelona', 'Spain', 'contact@barcelona.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (50, 'Manchester City', 'England', 'contact@manchestercity.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (51, 'Liverpool', 'England', 'contact@liverpool.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (52, 'Chelsea', 'England', 'contact@chelsea.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (53, 'Arsenal', 'England', 'contact@arsenal.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (54, 'Bayern Munich', 'Germany', 'contact@bayern.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (55, 'Borussia Dortmund', 'Germany', 'contact@dortmund.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (56, 'PSG', 'France', 'contact@psg.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (57, 'Juventus', 'Italy', 'contact@juventus.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (58, 'Inter Milan', 'Italy', 'contact@inter.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (59, 'AC Milan', 'Italy', 'contact@acmilan.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (60, 'Benfica', 'Portugal', 'contact@benfica.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (61, 'Porto', 'Portugal', 'contact@porto.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (62, 'Ajax', 'Netherlands', 'contact@ajax.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (63, 'RB Leipzig', 'Germany', 'contact@rbleipzig.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (64, 'Jamaica', 'Jamaica', 'contact@jamaica.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (65, 'Panama', 'Panama', 'contact@panama.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (66, 'Honduras', 'Honduras', 'contact@honduras.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (67, 'El Salvador', 'El Salvador', 'contact@elsalvador.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (68, 'Guatemala', 'Guatemala', 'contact@guatemala.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (69, 'Nicaragua', 'Nicaragua', 'contact@nicaragua.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (70, 'Haiti', 'Haiti', 'contact@haiti.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (71, 'Trinidad & Tobago', 'Trinidad & Tobago', 'contact@trinidad.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (72, 'Curacao', 'Curacao', 'contact@curacao.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (73, 'Martinique', 'Martinique', 'contact@martinique.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (74, 'Cuba', 'Cuba', 'contact@cuba.com', NULL);
INSERT INTO Teams (TeamId, Name, Country, Contact, CaptainId) VALUES (75, 'Bermuda', 'Bermuda', 'contact@bermuda.com', NULL);