CREATE TABLE Tournaments (
	TournamentId SERIAL PRIMARY KEY,
	Name VARCHAR(60) NOT NULL,
	Year SMALLINT NOT NULL,
	Location VARCHAR(100) NOT NULL,
	WinnerTeamId INT,

	CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Teams (
	TeamId SERIAL PRIMARY KEY,
	Name VARCHAR(60) NOT NULL,
	Country VARCHAR(60) NOT NULL,
	Contact VARCHAR(60) NOT NULL,
	CaptainId INT,

	CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Players (
	PlayerId SERIAL PRIMARY KEY,
	FirstName VARCHAR(60) NOT NULL,
	LastName VARCHAR(60) NOT NULL,
	DateOfBirth DATE NOT NULL,
	JerseyNumber SMALLINT NOT NULL,
	TeamId INT NOT NULL,

	CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Standings (
	StandingId SERIAL PRIMARY KEY,
	TournamentId INT NOT NULL,
	TeamId INT NOT NULL,
	Points SMALLINT DEFAULT 0,
	GoalDifference SMALLINT DEFAULT 0,

	CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Referees (
	RefereeId SERIAL PRIMARY KEY,
	FirstName VARCHAR(60) NOT NULL,
	LastName VARCHAR(60) NOT NULL,
	DateOfBirth DATE NOT NULL,
	Nationality VARCHAR(60) NOT NULL,

	CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Matches (
	MatchId SERIAL PRIMARY KEY,
	TournamentId INT NOT NULL,
	Team1Id INT NOT NULL,
	Team2Id INT NOT NULL,
	MatchDate DATE NOT NULL,
	MatchTime TIME NOT NULL,
	MatchTypeId INT NOT NULL,
	Team1Score SMALLINT,
	Team2Score SMALLINT,
	RefereeId INT NOT NULL,

	CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE MatchTypes (
	MatchTypeId SERIAL PRIMARY KEY,
	MatchType VARCHAR(40) UNIQUE NOT NULL,

	CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Events (
	EventId SERIAL PRIMARY KEY,
	MatchId INT NOT NULL,
	PlayerId INT NOT NULL,
	Type EventType NOT NULL,
	Minute SMALLINT NOT NULL,

	CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);