CREATE TRIGGER TournamentsUpdatedAt
BEFORE UPDATE ON Tournaments
FOR EACH ROW
EXECUTE FUNCTION SetUpdatedAt();

CREATE TRIGGER TeamsUpdatedAt
BEFORE UPDATE ON Teams
FOR EACH ROW
EXECUTE FUNCTION SetUpdatedAt();

CREATE TRIGGER PlayersUpdatedAt
BEFORE UPDATE ON Players
FOR EACH ROW
EXECUTE FUNCTION SetUpdatedAt();

CREATE TRIGGER StandingsUpdatedAt
BEFORE UPDATE ON Standings
FOR EACH ROW
EXECUTE FUNCTION SetUpdatedAt();

CREATE TRIGGER RefereesUpdatedAt
BEFORE UPDATE ON Referees
FOR EACH ROW
EXECUTE FUNCTION SetUpdatedAt();

CREATE TRIGGER MatchesUpdatedAt
BEFORE UPDATE ON Matches
FOR EACH ROW
EXECUTE FUNCTION SetUpdatedAt();

CREATE TRIGGER MatchTypesUpdatedAt
BEFORE UPDATE ON MatchTypes
FOR EACH ROW
EXECUTE FUNCTION SetUpdatedAt();

CREATE TRIGGER EventsUpdatedAt
BEFORE UPDATE ON Events
FOR EACH ROW
EXECUTE FUNCTION SetUpdatedAt();

CREATE TRIGGER MatchScore
BEFORE INSERT OR UPDATE ON Matches
FOR EACH ROW
EXECUTE FUNCTION CalculateMatchScore();

CREATE TRIGGER TeamStandings
AFTER INSERT OR UPDATE ON Matches
FOR EACH ROW
EXECUTE FUNCTION UpdateStandings();

CREATE TRIGGER TournamentWinner
AFTER INSERT OR UPDATE OF Team1Score, Team2Score
ON Matches
FOR EACH ROW
EXECUTE FUNCTION SetTournamentWinner();

CREATE TRIGGER CheckCaptain
BEFORE INSERT OR UPDATE ON Teams
FOR EACH ROW
EXECUTE FUNCTION CheckCaptainTeam();